title: Our Stroy of life
subtitle: A tree-hole being told the wonder
description: 故事 人生
author: Mitchell Yound
language: zh-cn
timezone: Japan

url: https://www.ourstoryof.life
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy

# Hexo localsearch
search:
  path: search.xml
  field: all

# Hexo generator feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

highlight:
  enable: true
  hljs: true # 添加这一行！
  line_number: true
  auto_detect: true
  tab_replace:

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn